### ISSUE TITLE
Não está funcionando main

### ISSUE THREAD

**Issue by Pcolombini** [pablomtlima/descomplicando#1]
Essa semana a extensão parou de funcionar, estava sendo de ótima ajuda, tenho pouco conhecimento e não consegui identificar o motivo.

Mas no console aparece o seguinte erro:
Uncaught TypeError: Failed to execute 'insertAdjacentElement' on 'Element': parameter 2 is not of type 'Element'.
    at <anonymous>:5:8
    at <anonymous>:8:3
(anonymous) @ VM15560:5
(anonymous) @ VM15560:8

(() => {
    console.log('habilitar')
    const resposta = document.querySelector('.solution__professor')
    const ol = document.querySelector('.question__alternatives')    
   ***(ERRO nessa Linha)*** ol.insertAdjacentElement('beforeend', resposta)
    resposta.removeAttribute('style', 'display: none;')

})()

Obrigado desde já

**Comment by pablomtlima** [comment]
Obrigado pelo feedback

**Comment by Pcolombini** [comment]
Obrigado pessoal
